scalaVersion := "3.2.0"
version      := "0.1.0"
name         := "zio-graph"

libraryDependencies += "dev.zio"            %% "zio"                % "2.0.9"
libraryDependencies += "dev.zio"            %% "zio-logging-slf4j2" % "2.1.10"
libraryDependencies += "dev.zio"            %% "zio-json"           % "0.4.2"
libraryDependencies += "dev.zio"            %% "zio-prelude"        % "1.0.0-RC16"
libraryDependencies += "io.github.iltotore" %% "iron"               % "2.0.0"
libraryDependencies += "io.github.iltotore" %% "iron-zio"           % "2.0.0"
